const menuarteuwu = (prefix, sender) => {
        return `
LOGOS BY: LIGHT
╔══════════════╗
║➩ ❍ ${prefix}videtexto
║➩ ❍ ${prefix}creavideoxd
║➩ ❍ ${prefix}logocosmic
║➩ ❍ ${prefix}fraseedit
║➩ ❍ ${prefix}shadow
║➩ ❍ ${prefix}gneon
║➩ ❍ ${prefix}matrixlogo
║➩ ❍ ${prefix}cup
║➩ ❍ ${prefix}cup1
║➩ ❍ ${prefix}romance
║➩ ❍ ${prefix}smoke
║➩ ❍ ${prefix}burnpaper
║➩ ❍ ${prefix}lovemessage
║➩ ❍ ${prefix}undergrass
║➩ ❍ ${prefix}love
║➩ ❍ ${prefix}coffe
║➩ ❍ ${prefix}woodheart
║➩ ❍ ${prefix}woodenboard
║➩ ❍ ${prefix}summer3d
║➩ ❍ ${prefix}wolfmetal
║➩ ❍ ${prefix}nature3d
║➩ ❍ ${prefix}underwater
║➩ ❍ ${prefix}golderrose
║➩ ❍ ${prefix}summernature
║➩ ❍ ${prefix}letterleaves
║➩ ❍ ${prefix}glowingneon
║➩ ❍ ${prefix}fallleaves
║➩ ❍ ${prefix}flamming
║➩ ❍ ${prefix}harrypotter
║➩ ❍ ${prefix}carvedwood
║➩ ❍ ${prefix}blackpink
║➩ ❍ ${prefix}neon
║➩ ❍ ${prefix}greenneon
║➩ ❍ ${prefix}advanceglow
║➩ ❍ ${prefix}futureneon
║➩ ❍ ${prefix}sandwriting
║➩ ❍ ${prefix}sandsummer
║➩ ❍ ${prefix}sandengraved
║➩ ❍ ${prefix}metaldark
║➩ ❍ ${prefix}neonlight
║➩ ❍ ${prefix}holographic
║➩ ❍ ${prefix}text1917
║➩ ❍ ${prefix}minion
║➩ ❍ ${prefix}deluxesilver
║➩ ❍ ${prefix}newyearcard
║➩ ❍ ${prefix}bloodfrosted
║➩ ❍ ${prefix}halloween
║➩ ❍ ${prefix}jokerlogo
║➩ ❍ ${prefix}fireworksparkle
║➩ ❍ ${prefix}natureleaves
║➩ ❍ ${prefix}bokeh
║➩ ❍ ${prefix}toxic
║➩ ❍ ${prefix}strawberry
║➩ ❍ ${prefix}box3d
║➩ ❍ ${prefix}roadwarning
║➩ ❍ ${prefix}breakwall
║➩ ❍ ${prefix}icecold
║➩ ❍ ${prefix}luxury
║➩ ❍ ${prefix}cloud
║➩ ❍ ${prefix}summersand
║➩ ❍ ${prefix}horrorblood
║➩ ❍ ${prefix}thunder
║➩ ❍ ${prefix}bannerlol
║➩ ❍ ${prefix}arcade8bit
║➩ ❍ ${prefix}writegalacy
║➩ ❍ ${prefix}textbyname
║➩ ❍ ${prefix}galaxybat
║➩ ❍ ${prefix}snow3d
║➩ ❍ ${prefix}birthdayday
║➩ ❍ ${prefix}goldplaybutton
║➩ ❍ ${prefix}silverplaybutton
║➩ ❍ ${prefix}wallgravity
║➩ ❍ ${prefix}steel3d
║➩ ❍ ${prefix}wolflogo
║➩ ❍ ${prefix}lionlogo
║➩ ❍ ${prefix}ninjalogo
║➩ ❍ ${prefix}marvelstudio
║➩ ❍ ${prefix}space
║➩ ❍ ${prefix}avenger
║➩ ❍ ${prefix}wooden3d
║➩ ❍ ${prefix}starsnight
║➩ ❍ ${prefix}textcake
║➩ ❍ ${prefix}glittergold
║➩ ❍ ${prefix}metallogo
║➩ ❍ ${prefix}noeltext
║➩ ❍ ${prefix}greenbush
║➩ ❍ ${prefix}glossychrome
║➩ ❍ ${prefix}greenneon
║➩ ❍ ${prefix}hologram3d
║➩ ❍ ${prefix}galaxystyle
║➩ ❍ ${prefix}birthdaycake
║➩ ❍ ${prefix}heartshaped
║➩ ❍ ${prefix}royaltext
║➩ ❍ ${prefix}puppycute
║➩ ❍ ${prefix}beautifulflower
║➩ ❍ ${prefix}lighttext
║➩ ❍ ${prefix}galaxywallpaper
║➩ ❍ ${prefix}luxurygold
║➩ ❍ ${prefix}watercolor
║➩ ❍ ${prefix}multicolor3d
║➩ ❍ ${prefix}wetglass
║➩ ❍ ${prefix}pubg
║➩ ❍ ${prefix}battlefield4
║➩ ❍ ${prefix}pornhub
║➩ ❍ ${prefix}glitch
╚══════════════╝

  
  _*uso de comandos en un lapso de 10s minimo*_
`
}

exports.menuarteuwu = menuarteuwu
